AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  CalculatePeriodicStats:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::037275668898:role/service-role/CalculatePeriodicStats-role-k2jecb4h
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
